//sirven para describir que hacen en tuaplicaicon
export const ACTIVAR_GRILLA = "ACTIVAR_GRILLA";
export const BARCO_SELECCIONADO = "BARCO_SELECCIONADO";
export const GUARDAR_POSICION_ACTUAL = "GUARDAR_POSICION_ACTUAL";
export const SAVE_CELL_PAINT = "SAVE_CELL_PAINT";
export const CHANGUE_DIRECTION = "CHANGUE_DIRECTION";
export const DELETE_LISTED_BOAT = "DELETE_LISTED_BOAT";
export const ASIGNAR_CARRIER = "ASIGNAR_CARRIER";
export const ASIGNAR_CRUISERS1 = "ASIGNAR_CRUISERS1";
export const ASIGNAR_CRUISERS2 = "ASIGNAR_CRUISERS2";
export const ASIGNAR_CRUISERS3 = "ASIGNAR_CRUISERS3";
export const ASIGNAR_SUBMARINE = "ASIGNAR_SUBMARINE";
export const START_GAME = "START_GAME";
export const CHANGUE_TURN_HUMAN = "CHANGUE_TURN_HUMAN";
export const ADD_SELECTION_SHIT_HUMAN = "ADD_SELECTION_SHIT_HUMAN";
export const IMPACT_CARRIER = "IMPACT_CARRIER";
export const IMPACT_CRUISERS1 = "IMPACT_CRUISERS1";
export const IMPACT_CRUISERS2 = "IMPACT_CRUISERS2";
export const IMPACT_CRUISERS3 = "IMPACT_CRUISERS3";
export const IMPACT_SUBMARINE = "IMPACT_SUBMARINE";
export const LAST_IMPACT = "LAST_IMPACT";
export const IMPACT_CARRIER_CPU = "IMPACT_CARRIER_CPU";
export const IMPACT_CRUISERS1_CPU = "IMPACT_CRUISERS1_CPU";
export const IMPACT_CRUISERS2_CPU = "IMPACT_CRUISERS2_CPU";
export const IMPACT_CRUISERS3_CPU = "IMPACT_CRUISERS3_CPU";
export const IMPACT_SUBMARINE_CPU = "IMPACT_SUBMARINE_CPU";
export const ADD_SELECTION_CPU = "ADD_SELECTION_CPU";
export const ADD_CELL_RANDOM = "ADD_CELL_RANDOM";

/* export const SELECCIONAR_BARCO_EXITO = "SELECCIONAR_BARCO_EXITO";

export const SELECCIONAR_BARCO_ERROR = "SELECCIONAR_BARCO_ERROR";
export const COMENZAR_JUEGO = "COMENZAR_JUEGO"; */
