//sirven para describir que hacen en tuaplicaicon
export const ACTIVAR_GRILLA = "ACTIVAR_GRILLA";
export const BARCO_SELECCIONADO = "BARCO_SELECCIONADO";
export const GUARDAR_POSICION_ACTUAL = "GUARDAR_POSICION_ACTUAL";
export const GUARDAR_CELDAS_PINTAR = "GUARDAR_CELDAS_PINTAR";
export const CHANGUE_SENSE = "CHANGUE_SENSE";
export const DELETE_LISTED_BOAT = "DELETE_LISTED_BOAT";
export const ASIGNAR_CARRIER = "ASIGNAR_CARRIER";
export const ASIGNAR_CRUISERS1 = "ASIGNAR_CRUISERS1";
export const ASIGNAR_CRUISERS2 = "ASIGNAR_CRUISERS2";
export const ASIGNAR_CRUISERS3 = "ASIGNAR_CRUISERS3";
export const ASIGNAR_SUBMARINE = "ASIGNAR_SUBMARINE";
export const START_GAME = "START_GAME";

/* export const SELECCIONAR_BARCO_EXITO = "SELECCIONAR_BARCO_EXITO";

export const SELECCIONAR_BARCO_ERROR = "SELECCIONAR_BARCO_ERROR";
export const COMENZAR_JUEGO = "COMENZAR_JUEGO"; */
